### ISSUE TITLE
LED G & B control signals are crossed.

### ISSUE THREAD

**Issue by TomKeddie** [butterstick-fpga/butterstick-hardware#12]
In this schematic excerpt you can see LEDG is driving CATB and LEDB is driving CATG.  Is easily fixed in the platform definitions but the schematic labels could be updated to swap LEDG and LEDB for clarity.

![image](https://user-images.githubusercontent.com/4367175/145723344-32008ec6-9578-4157-a6ab-3083a9ea5332.png)

**Comment by nandland** [comment]
I found this issue as well... scratching my head wondering why the Blue LED is turning on when I specifically asked for green. :)

**Comment by gregdavill** [comment]
Thanks for picking this up Tom.

The easiest fix is to swap the signals from the FPGA to this page. Q2/Q3 will still control Blue/Green respectively. But now the signals are correctly named from the FPGA.
