### ISSUE TITLE
Assembled PCBs link don't work

### ISSUE THREAD

**Issue by LaneaLucy** [butterstick-fpga/butterstick-hardware#17]
When I open the link, I only get the homepage and when I search for butter stick on it, I only find the SYZYGY Breakout board for Butterstick

**Comment by gregdavill** [comment]
I'll check but this probably means that the first batch of boards has entirely sold out.

**Comment by LaneaLucy** [comment]
Is there any other option to get a preassembled one, maybe even with other ram chips? Found the MT41K512M16VRP-107 which should be pin compatible, except that one pin, that is NC is a extra address pin, but the schematic show, that this pin is already connected. And I would really like to get one with even more ram

**Comment by gregdavill** [comment]
Closing because the link on the main page now works again. (while stock is available)

I'm able to do rework for different RAM alterations. Just drop me an email, it's listed on my profile :+1:
