### ISSUE TITLE
Ethernet MDIO line needs pullup

### ISSUE THREAD

**Issue by gregdavill** [butterstick-fpga/butterstick-hardware#4]
Add a 1K-4k7 pull-up to the MDIO line to the PHY.

**Comment by Nightsd01** [comment]
Hey Greg, I am so impressed by this project but I have a quick question for you and couldn’t find a better place to ask. I’m a bit of a n00b with PCB design and I was wondering why some of the traces on your board seem to be so “squiggly” (for lack of a better word)?

Does it have something to do with avoiding signal interference? Or are you using it to make sure traces are of equal length even if they go to different places of the PCB?

![F3576EEC-0593-4DDD-81F0-FD1606435504](https://user-images.githubusercontent.com/8186991/70855245-b3d3c680-1e7c-11ea-84ed-b8cdbdd70351.jpeg)

**Comment by gregdavill** [comment]
They're meandering traces. They are used to ensure signals transmitted from one chip arrive at the same time on the receiving chip.
